"use client";

import { useState, useCallback } from "react";
import { marked } from "marked";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  FileText,
  Download,
  RefreshCw,
  Loader2,
  ChevronDown,
  ChevronUp,
} from "lucide-react";
import { format } from "date-fns";
import { useToast } from "@/components/ui/use-toast";
import { financeOverviewService } from "@/lib/data";
import type { MonthlyOverviewResponse } from "@/types";

// ── Default template ──────────────────────────────────────────────────────────
// Placeholders: {{month}}, {{month_display}}, {{generated_at}},
// {{total_student_revenue}}, {{total_admission_fees}}, {{total_collected}},
// {{total_teacher_payouts}}, {{net_revenue}}, {{total_staff_commissions}},
// {{total_expenses}}, {{institute_income}},
// {{class_breakdown_table}}, {{expense_breakdown_table}}

const DEFAULT_TEMPLATE = `# Monthly Financial Report
## {{month_display}}

**Generated:** {{generated_at}}

---

## Executive Summary

| Metric | Amount |
|--------|--------|
| Student Class Revenue | LKR {{total_student_revenue}} |
| Admission Fees | LKR {{total_admission_fees}} |
| **Total Collected** | **LKR {{total_collected}}** |
| Teacher Payouts | LKR {{total_teacher_payouts}} |
| **Net Revenue** | **LKR {{net_revenue}}** |
| Staff Commissions | LKR {{total_staff_commissions}} |
| Expenses | LKR {{total_expenses}} |
| **Institute Income** | **LKR {{institute_income}}** |

---

## Class Revenue Breakdown

{{class_breakdown_table}}

---

## Expenses by Category

{{expense_breakdown_table}}

---

*This report was generated by the Academy Management System on {{generated_at}}.*
`;

// ── Number formatting ─────────────────────────────────────────────────────────
const fmt = (n: number) =>
  n.toLocaleString("en-LK", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });

// ── Build the class breakdown markdown table ──────────────────────────────────
function buildClassTable(data: MonthlyOverviewResponse): string {
  if (data.class_breakdown.length === 0) {
    return "*No class payments recorded for this month.*";
  }
  const header =
    "| Class | Teacher | Students | Revenue (LKR) | Payout % | Expected Payout (LKR) | Actual Payout (LKR) | Status |\n" +
    "|-------|---------|----------|---------------|----------|-----------------------|---------------------|--------|";
  const rows = data.class_breakdown
    .sort((a, b) => b.total_revenue - a.total_revenue)
    .map(
      (c) =>
        `| ${c.class_name} | ${c.teacher_name} | ${c.student_count} | ${fmt(c.total_revenue)} | ${c.payout_percentage}% | ${fmt(c.expected_payout)} | ${fmt(c.actual_payout)} | ${c.payout_status} |`,
    )
    .join("\n");

  const totalsRow =
    `| **Total** | | | **${fmt(data.total_student_revenue)}** | | | **${fmt(data.total_teacher_payouts)}** | |`;

  return [header, rows, totalsRow].join("\n");
}

// ── Build the expense breakdown markdown table ────────────────────────────────
function buildExpenseTable(data: MonthlyOverviewResponse): string {
  const entries = Object.entries(data.expense_by_category);
  if (entries.length === 0) {
    return "*No expenses recorded for this month.*";
  }
  const header =
    "| Category | Amount (LKR) |\n|----------|--------------|";
  const rows = entries
    .sort(([, a], [, b]) => b - a)
    .map(([cat, amount]) => `| ${cat.replace("_", " ")} | ${fmt(amount)} |`)
    .join("\n");
  const totalRow = `| **Total** | **${fmt(data.total_expenses)}** |`;
  return [header, rows, totalRow].join("\n");
}

// ── Populate template with real data ─────────────────────────────────────────
function populateTemplate(
  template: string,
  data: MonthlyOverviewResponse,
): string {
  const monthDate = new Date(data.month + "-01");
  const monthDisplay = format(monthDate, "MMMM yyyy");
  const generatedAt = format(new Date(data.generated_at), "PPPp");

  return template
    .replace(/\{\{month\}\}/g, data.month)
    .replace(/\{\{month_display\}\}/g, monthDisplay)
    .replace(/\{\{generated_at\}\}/g, generatedAt)
    .replace(/\{\{total_student_revenue\}\}/g, fmt(data.total_student_revenue))
    .replace(/\{\{total_admission_fees\}\}/g, fmt(data.total_admission_fees))
    .replace(/\{\{total_collected\}\}/g, fmt(data.total_collected))
    .replace(/\{\{total_teacher_payouts\}\}/g, fmt(data.total_teacher_payouts))
    .replace(/\{\{net_revenue\}\}/g, fmt(data.net_revenue))
    .replace(
      /\{\{total_staff_commissions\}\}/g,
      fmt(data.total_staff_commissions),
    )
    .replace(/\{\{total_expenses\}\}/g, fmt(data.total_expenses))
    .replace(/\{\{institute_income\}\}/g, fmt(data.institute_income))
    .replace(/\{\{class_breakdown_table\}\}/g, buildClassTable(data))
    .replace(/\{\{expense_breakdown_table\}\}/g, buildExpenseTable(data));
}

// ── PDF print styles (injected into the print window) ────────────────────────
const PRINT_STYLES = `
  * { box-sizing: border-box; }
  body {
    font-family: 'Segoe UI', Arial, sans-serif;
    font-size: 12px;
    line-height: 1.6;
    color: #1a1a1a;
    max-width: 900px;
    margin: 0 auto;
    padding: 24px;
  }
  h1 { font-size: 22px; margin-bottom: 4px; color: #111; }
  h2 { font-size: 16px; margin-top: 24px; margin-bottom: 8px; color: #222; border-bottom: 1px solid #ccc; padding-bottom: 4px; }
  h3 { font-size: 14px; margin-top: 16px; color: #333; }
  p { margin: 6px 0; }
  hr { border: none; border-top: 1px solid #ddd; margin: 20px 0; }
  table { border-collapse: collapse; width: 100%; margin: 12px 0; font-size: 11px; }
  th { background: #f0f0f0; font-weight: 600; text-align: left; padding: 6px 8px; border: 1px solid #ccc; }
  td { padding: 5px 8px; border: 1px solid #ddd; }
  tr:nth-child(even) td { background: #fafafa; }
  strong { font-weight: 700; }
  em { color: #555; font-style: italic; }
  @media print {
    body { padding: 0; }
    @page { margin: 1.5cm; }
  }
`;

// ── Component ─────────────────────────────────────────────────────────────────
export function MonthlyReportGenerator() {
  const currentMonth = new Date().toISOString().substring(0, 7);
  const [month, setMonth] = useState(currentMonth);
  const [template, setTemplate] = useState(DEFAULT_TEMPLATE);
  const [showTemplate, setShowTemplate] = useState(false);
  const [data, setData] = useState<MonthlyOverviewResponse | null>(null);
  const [populatedMd, setPopulatedMd] = useState<string | null>(null);
  const [renderedHtml, setRenderedHtml] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const { toast } = useToast();

  const generate = useCallback(async () => {
    setLoading(true);
    try {
      const result = await financeOverviewService.getMonthlyOverview(month);
      setData(result);
      const populated = populateTemplate(template, result);
      setPopulatedMd(populated);
      const html = await marked(populated);
      setRenderedHtml(html as string);
    } catch {
      toast({
        title: "Error",
        description: "Failed to generate report",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  }, [month, template, toast]);

  const downloadPdf = useCallback(() => {
    if (!renderedHtml) return;
    const printWindow = window.open("", "_blank", "width=900,height=700");
    if (!printWindow) {
      toast({
        title: "Blocked",
        description:
          "Please allow pop-ups for this site to download the PDF.",
        variant: "destructive",
      });
      return;
    }
    const monthDisplay = data
      ? format(new Date(data.month + "-01"), "MMMM yyyy")
      : month;
    printWindow.document.write(`<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Monthly Report — ${monthDisplay}</title>
  <style>${PRINT_STYLES}</style>
</head>
<body>${renderedHtml}</body>
</html>`);
    printWindow.document.close();
    // Give the browser a moment to render before printing
    printWindow.addEventListener("load", () => {
      printWindow.focus();
      printWindow.print();
    });
    // Fallback if load already fired
    setTimeout(() => {
      try {
        printWindow.focus();
        printWindow.print();
      } catch {
        /* already printed */
      }
    }, 500);
  }, [renderedHtml, data, month, toast]);

  const resetTemplate = () => {
    setTemplate(DEFAULT_TEMPLATE);
    setPopulatedMd(null);
    setRenderedHtml(null);
  };

  return (
    <div className="space-y-6">
      {/* Controls */}
      <div className="flex flex-wrap items-end gap-4">
        <div>
          <Label htmlFor="report-month">Month</Label>
          <Input
            id="report-month"
            type="month"
            value={month}
            onChange={(e) => {
              setMonth(e.target.value);
              setRenderedHtml(null);
            }}
            className="w-44"
          />
        </div>
        <Button onClick={generate} disabled={loading}>
          {loading ? (
            <Loader2 className="h-4 w-4 animate-spin mr-2" />
          ) : (
            <FileText className="h-4 w-4 mr-2" />
          )}
          Generate Report
        </Button>
        {renderedHtml && (
          <Button variant="outline" onClick={downloadPdf}>
            <Download className="h-4 w-4 mr-2" />
            Download PDF
          </Button>
        )}
      </div>

      {/* Template editor (collapsible) */}
      <Card>
        <CardHeader
          className="cursor-pointer select-none"
          onClick={() => setShowTemplate((v) => !v)}
        >
          <CardTitle className="flex items-center justify-between text-base">
            <span>Markdown Template</span>
            <div className="flex items-center gap-2">
              {showTemplate && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={(e) => {
                    e.stopPropagation();
                    resetTemplate();
                  }}
                  className="text-xs h-7"
                >
                  <RefreshCw className="h-3 w-3 mr-1" />
                  Reset to default
                </Button>
              )}
              {showTemplate ? (
                <ChevronUp className="h-4 w-4 text-muted-foreground" />
              ) : (
                <ChevronDown className="h-4 w-4 text-muted-foreground" />
              )}
            </div>
          </CardTitle>
          {!showTemplate && (
            <p className="text-xs text-muted-foreground">
              Click to expand and customize the report template. Available
              placeholders:{" "}
              <code className="text-xs bg-muted px-1 rounded">
                {"{{month_display}}"}
              </code>
              ,{" "}
              <code className="text-xs bg-muted px-1 rounded">
                {"{{total_collected}}"}
              </code>
              ,{" "}
              <code className="text-xs bg-muted px-1 rounded">
                {"{{institute_income}}"}
              </code>
              ,{" "}
              <code className="text-xs bg-muted px-1 rounded">
                {"{{class_breakdown_table}}"}
              </code>
              , and more.
            </p>
          )}
        </CardHeader>
        {showTemplate && (
          <CardContent>
            <Textarea
              value={template}
              onChange={(e) => {
                setTemplate(e.target.value);
                setRenderedHtml(null);
              }}
              rows={24}
              className="font-mono text-xs resize-y"
              spellCheck={false}
            />
            <p className="text-xs text-muted-foreground mt-2">
              Changes to the template take effect on next Generate. The template
              supports standard Markdown: headers, bold, tables, and horizontal
              rules.
            </p>
          </CardContent>
        )}
      </Card>

      {/* Rendered preview */}
      {renderedHtml && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center justify-between">
              <span>Preview</span>
              <Button size="sm" onClick={downloadPdf} variant="outline">
                <Download className="h-4 w-4 mr-2" />
                Download PDF
              </Button>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div
              className="prose prose-sm dark:prose-invert max-w-none border rounded-lg p-6 bg-white dark:bg-zinc-950
                [&_table]:border-collapse [&_table]:w-full [&_table]:text-sm
                [&_th]:bg-muted [&_th]:font-semibold [&_th]:text-left [&_th]:p-2 [&_th]:border [&_th]:border-border
                [&_td]:p-2 [&_td]:border [&_td]:border-border
                [&_tr:nth-child(even)_td]:bg-muted/30
                [&_h1]:text-2xl [&_h1]:font-bold [&_h1]:mb-1
                [&_h2]:text-lg [&_h2]:font-semibold [&_h2]:mt-6 [&_h2]:mb-3 [&_h2]:border-b [&_h2]:pb-1
                [&_hr]:border-border [&_hr]:my-5
                [&_strong]:font-semibold
                [&_em]:text-muted-foreground [&_em]:text-xs
                [&_p]:leading-relaxed"
              dangerouslySetInnerHTML={{ __html: renderedHtml }}
            />
          </CardContent>
        </Card>
      )}
    </div>
  );
}
